# Generated by Django 5.2.4 on 2025-08-03 08:58

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileMeta',
            fields=[
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('mongo_id', models.CharField(max_length=64, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files_set.category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
