# Generated by Django 5.2.4 on 2025-09-10 03:11

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_set', '0003_remove_filemeta_mongo_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.CreateModel(
            name='Labels',
            fields=[
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('resources_name', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='资源名称')),
                ('resources_size', models.BigIntegerField(blank=True, null=True, verbose_name='资源大小')),
                ('resources_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='资源类型')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files_set.category', verbose_name='分类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name_plural': 'Resources',
                'db_table': 'resources',
            },
        ),
        migrations.DeleteModel(
            name='FileMeta',
        ),
    ]
