# Generated by Django 5.2.4 on 2025-08-02 11:18

import account.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='avatar')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='username')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='nickname')),
                ('wx_openid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='wx_openid')),
                ('wx_unionid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='wx_unionid')),
                ('wx_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='wx_nickname')),
                ('wx_avatar_url', models.URLField(blank=True, null=True, verbose_name='wx_avatar_url')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='account_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='account_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('permission_name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('permission_code', models.CharField(max_length=100, unique=True, verbose_name='权限code')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='account.custompermission', verbose_name='权限')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.role', verbose_name='roles'),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('system_name', models.CharField(max_length=100, verbose_name='系统名称')),
                ('system_code', models.CharField(max_length=50, unique=True, verbose_name='系统唯一标识')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_systems', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='systems',
            field=models.ManyToManyField(blank=True, related_name='users', to='account.system', verbose_name='systems'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['unified_uuid'], name='idx_user_unified_uuid'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'username'], name='idx_user_deleted_username'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'nickname'], name='idx_user_deleted_nickname'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'email'], name='idx_user_deleted_email'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'phone'], name='idx_user_deleted_phone'),
        ),
    ]
