# Generated by Django 5.2.4 on 2025-08-03 04:10

import account.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('unified_uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='phone')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('avatar', models.URLField(blank=True, db_index=True, null=True, verbose_name='avatar')),
                ('username', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='username')),
                ('nickname', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='nickname')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='is_staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
