# Generated by Django 5.2.4 on 2025-08-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files_set', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemeta',
            name='file_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='filemeta',
            name='file_path',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='filemeta',
            name='mongo_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
