# Generated by Django 5.2.4 on 2025-08-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files_set', '0002_filemeta_file_hash_filemeta_file_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemeta',
            name='mongo_id',
        ),
    ]
