# Generated by Django 5.2.4 on 2025-08-02 06:35

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unified_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('permission_name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('permission_code', models.CharField(max_length=100, unique=True, verbose_name='权限code')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unified_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('system_name', models.CharField(max_length=100, verbose_name='系统名称')),
                ('system_code', models.CharField(max_length=50, unique=True, verbose_name='系统唯一标识')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unified_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='account.custompermission', verbose_name='权限')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('unified_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='全系统唯一标识')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='当前系统唯一标识')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除: True 已经删除 False 未删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='avatar')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='username')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='nickname')),
                ('wx_openid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='wx_openid')),
                ('wx_unionid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='wx_unionid')),
                ('wx_nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='wx_nickname')),
                ('wx_avatar_url', models.URLField(blank=True, null=True, verbose_name='wx_avatar_url')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is_staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='account_users', to='auth.group', verbose_name='groups')),
                ('roles', models.ManyToManyField(blank=True, related_name='users', to='account.role', verbose_name='roles')),
                ('systems', models.ManyToManyField(blank=True, related_name='users', to='account.system', verbose_name='systems')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='account_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'indexes': [models.Index(fields=['unified_uuid'], name='idx_user_unified_uuid'), models.Index(fields=['is_deleted', 'username'], name='idx_user_deleted_username'), models.Index(fields=['is_deleted', 'nickname'], name='idx_user_deleted_nickname'), models.Index(fields=['is_deleted', 'email'], name='idx_user_deleted_email'), models.Index(fields=['is_deleted', 'phone'], name='idx_user_deleted_phone')],
            },
        ),
    ]
