# Generated by Django 5.2.4 on 2025-08-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_deleted', 'email', 'nickname', 'wx_nickname', 'username'], name='idx_user_list'),
        ),
    ]
