# Generated by Django 5.2.4 on 2025-08-03 03:35

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_idx_user_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompermission',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='permission_code',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='权限code'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='permission_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='权限名称'),
        ),
        migrations.AlterField(
            model_name='custompermission',
            name='uuid',
            field=models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_enable',
            field=models.BooleanField(db_index=True, default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='角色名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='uuid',
            field=models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识'),
        ),
        migrations.AlterField(
            model_name='system',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_code',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='系统唯一标识'),
        ),
        migrations.AlterField(
            model_name='system',
            name='system_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='系统名称'),
        ),
        migrations.AlterField(
            model_name='system',
            name='uuid',
            field=models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, db_index=True, null=True, verbose_name='avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='is_active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除: True 已经删除 False 未删除'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, verbose_name='is_staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.CharField(db_index=True, default=account.models.create_uuid, editable=False, max_length=25, primary_key=True, serialize=False, verbose_name='当前系统唯一标识'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wx_avatar_url',
            field=models.URLField(blank=True, db_index=True, null=True, verbose_name='wx_avatar_url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wx_nickname',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='wx_nickname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wx_openid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='wx_openid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wx_unionid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True, verbose_name='wx_unionid'),
        ),
    ]
